// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package main

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "CanBackup",
			Fn:      v.CanBackup,
			OutArgs: []string{"can"},
		},
		{
			Name:    "CanRestore",
			Fn:      v.CanRestore,
			OutArgs: []string{"can"},
		},
		{
			Name: "StartBackup",
			Fn:   v.StartBackup,
		},
		{
			Name: "StartRestore",
			Fn:   v.StartRestore,
		},
	}
}
