// Code generated by "dbusutil-gen -type Manager manager.go"; DO NOT EDIT.

package main

func (v *Manager) setPropBackingUp(value bool) (changed bool) {
	if v.BackingUp != value {
		v.BackingUp = value
		v.emitPropChangedBackingUp(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedBackingUp(value bool) error {
	return v.service.EmitPropertyChanged(v, "BackingUp", value)
}

func (v *Manager) setPropRestoring(value bool) (changed bool) {
	if v.Restoring != value {
		v.Restoring = value
		v.emitPropChangedRestoring(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedRestoring(value bool) error {
	return v.service.EmitPropertyChanged(v, "Restoring", value)
}

func (v *Manager) setPropConfigValid(value bool) (changed bool) {
	if v.ConfigValid != value {
		v.ConfigValid = value
		v.emitPropChangedConfigValid(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedConfigValid(value bool) error {
	return v.service.EmitPropertyChanged(v, "ConfigValid", value)
}

func (v *Manager) setPropBackupVersion(value string) (changed bool) {
	if v.BackupVersion != value {
		v.BackupVersion = value
		v.emitPropChangedBackupVersion(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedBackupVersion(value string) error {
	return v.service.EmitPropertyChanged(v, "BackupVersion", value)
}

func (v *Manager) setPropBackupTime(value int64) (changed bool) {
	if v.BackupTime != value {
		v.BackupTime = value
		v.emitPropChangedBackupTime(value)
		return true
	}
	return false
}

func (v *Manager) emitPropChangedBackupTime(value int64) error {
	return v.service.EmitPropertyChanged(v, "BackupTime", value)
}
